/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_irri_test_Hdf5LibraryLoadTest */

#ifndef _Included_org_irri_test_Hdf5LibraryLoadTest
#define _Included_org_irri_test_Hdf5LibraryLoadTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_irri_test_Hdf5LibraryLoadTest
 * Method:    testNativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_irri_test_Hdf5LibraryLoadTest_testNativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
